import { Client, Account, Databases, ID, Query, Permission, Role } from 'appwrite'

const ENDPOINT = 'https://nyc.cloud.appwrite.io/v1'
const PROJECT_ID = '6aa5127e001ea31b0f77'
const DATABASE_ID = '6aaa2edb002d5a668746'
const COLLECTIONS = {
  users: '6aaa2a34003681b87ac5', moments: '6aa517d80020820efcb0', participants: '6aaa2ced00214fa332b5',
  reactions: '6aaa2ffd00040fbf4bee', follows: '6aaa30da000a4707eba3', reports: '6aaa32a1000082d07a73', comments: '6aaa2edb002d5a668746'
}
const client = new Client().setEndpoint(ENDPOINT).setProject(PROJECT_ID)
export const account = new Account(client)
export const databases = new Databases(client)

export async function getCurrentUser(){try{return await account.get()}catch{return null}}
export async function login(email,password){return account.createEmailPasswordSession(email,password)}
export async function register(email,password,name){const u=await account.create(ID.unique(),email,password,name);await account.createEmailPasswordSession(email,password);return u}
export async function logout(){try{await account.deleteSession('current')}catch{}}
export async function ensureUserDocument(user){try{return await databases.getDocument(DATABASE_ID,COLLECTIONS.users,user.$id)}catch{};return databases.createDocument(DATABASE_ID,COLLECTIONS.users,user.$id,{userId:user.$id,username:(user.name||user.email?.split('@')[0]||'world').slice(0,30),displayName:(user.name||'WORLD User').slice(0,100),avatarId:'',bio:'',visibility:'public',followersCount:0,followingCount:0,momentsCount:0},[Permission.read(Role.any()),Permission.update(Role.user(user.$id))])}
export async function getUserProfile(userId){return databases.getDocument(DATABASE_ID,COLLECTIONS.users,userId)}
export async function updateUserProfile(userId,data){return databases.updateDocument(DATABASE_ID,COLLECTIONS.users,userId,{username:data.username,displayName:data.displayName,bio:data.bio,visibility:data.visibility})}
export async function listUsers(search=''){const r=await databases.listDocuments(DATABASE_ID,COLLECTIONS.users,[Query.limit(100)]);const q=search.trim().toLowerCase();return q?r.documents.filter(u=>(u.username+' '+(u.displayName||'')).toLowerCase().includes(q)).slice(0,30):r.documents.slice(0,30)}
export async function getMoment(momentId){return databases.getDocument(DATABASE_ID,COLLECTIONS.moments,momentId)}
export async function listNotifications(userId){const mine=await listUserMoments(userId);if(!mine.length)return [];const ids=mine.slice(0,20).map(m=>m.$id);const out=[];for(const [col,type,field] of [[COLLECTIONS.participants,'joined','momentId'],[COLLECTIONS.reactions,'reacted','momentId'],[COLLECTIONS.comments,'commented','momentId']]){for(const id of ids){try{const r=await databases.listDocuments(DATABASE_ID,col,[Query.equal(field,id),Query.orderDesc('createdAt'),Query.limit(20)]);r.documents.forEach(x=>{if(x.userId!==userId)out.push({...x,_type:type})})}catch{}}}return out.sort((a,b)=>new Date(b.createdAt||b.$createdAt)-new Date(a.createdAt||a.$createdAt)).slice(0,30)}
export async function listMoments(){const r=await databases.listDocuments(DATABASE_ID,COLLECTIONS.moments,[Query.equal('status','active'),Query.orderDesc('$createdAt'),Query.limit(100)]);const now=Date.now();return r.documents.filter(m=>!m.expiresAt||new Date(m.expiresAt).getTime()>now)}
export async function listUserMoments(userId){const r=await databases.listDocuments(DATABASE_ID,COLLECTIONS.moments,[Query.equal('ownerId',userId),Query.orderDesc('$createdAt'),Query.limit(50)]);return r.documents}
export async function createMoment(userId,data){return databases.createDocument(DATABASE_ID,COLLECTIONS.moments,ID.unique(),{ownerId:userId,visibility:data.visibility||'nearby',title:data.title,description:data.description||'',category:data.category||'do',imageUrl:'',latitude:data.latitude||'',longitude:data.longitude||'',expiresAt:data.expiresAt||new Date(Date.now()+2*60*60*1000).toISOString(),participantsCount:0,reactionsCount:0,commentsCount:0,status:'active'},[Permission.read(Role.any()),Permission.update(Role.user(userId)),Permission.delete(Role.user(userId))])}
export async function joinMoment(momentId,userId){const e=await databases.listDocuments(DATABASE_ID,COLLECTIONS.participants,[Query.equal('momentId',momentId),Query.equal('userId',userId),Query.limit(1)]);if(e.documents.length)return e.documents[0];const d=await databases.createDocument(DATABASE_ID,COLLECTIONS.participants,ID.unique(),{momentId,userId,joinedAt:new Date().toISOString(),status:'joined'},[Permission.read(Role.any()),Permission.update(Role.user(userId)),Permission.delete(Role.user(userId))]);const m=await databases.getDocument(DATABASE_ID,COLLECTIONS.moments,momentId);await databases.updateDocument(DATABASE_ID,COLLECTIONS.moments,momentId,{participantsCount:Number(m.participantsCount||0)+1});return d}
export async function reactToMoment(momentId,userId,type='like'){const e=await databases.listDocuments(DATABASE_ID,COLLECTIONS.reactions,[Query.equal('momentId',momentId),Query.equal('userId',userId),Query.limit(1)]);if(e.documents.length)return e.documents[0];const d=await databases.createDocument(DATABASE_ID,COLLECTIONS.reactions,ID.unique(),{momentId,userId,type,createdAt:new Date().toISOString()},[Permission.read(Role.any()),Permission.delete(Role.user(userId))]);const m=await databases.getDocument(DATABASE_ID,COLLECTIONS.moments,momentId);await databases.updateDocument(DATABASE_ID,COLLECTIONS.moments,momentId,{reactionsCount:Number(m.reactionsCount||0)+1});return d}
export async function addComment(momentId,userId,text){const d=await databases.createDocument(DATABASE_ID,COLLECTIONS.comments,ID.unique(),{momentId,userId,text,createdAt:new Date().toISOString()},[Permission.read(Role.any()),Permission.update(Role.user(userId)),Permission.delete(Role.user(userId))]);const m=await databases.getDocument(DATABASE_ID,COLLECTIONS.moments,momentId);await databases.updateDocument(DATABASE_ID,COLLECTIONS.moments,momentId,{commentsCount:Number(m.commentsCount||0)+1});return d}
export async function listComments(momentId){const r=await databases.listDocuments(DATABASE_ID,COLLECTIONS.comments,[Query.equal('momentId',momentId),Query.orderDesc('createdAt'),Query.limit(30)]);return r.documents}
export async function followUser(userId,targetUserId){if(userId===targetUserId)throw new Error('You cannot follow yourself.');const e=await databases.listDocuments(DATABASE_ID,COLLECTIONS.follows,[Query.equal('userId',userId),Query.equal('targetUserId',targetUserId),Query.limit(1)]);if(e.documents.length)return e.documents[0];const d=await databases.createDocument(DATABASE_ID,COLLECTIONS.follows,ID.unique(),{userId,targetUserId,createdAt:new Date().toISOString()},[Permission.read(Role.any()),Permission.delete(Role.user(userId))]);const [me,target]=await Promise.all([getUserProfile(userId),getUserProfile(targetUserId)]);await Promise.all([databases.updateDocument(DATABASE_ID,COLLECTIONS.users,userId,{followingCount:Number(me.followingCount||0)+1}),databases.updateDocument(DATABASE_ID,COLLECTIONS.users,targetUserId,{followersCount:Number(target.followersCount||0)+1})]);return d}
export async function unfollowUser(userId,targetUserId){const e=await databases.listDocuments(DATABASE_ID,COLLECTIONS.follows,[Query.equal('userId',userId),Query.equal('targetUserId',targetUserId),Query.limit(1)]);if(!e.documents.length)return;await databases.deleteDocument(DATABASE_ID,COLLECTIONS.follows,e.documents[0].$id);const [me,target]=await Promise.all([getUserProfile(userId),getUserProfile(targetUserId)]);await Promise.all([databases.updateDocument(DATABASE_ID,COLLECTIONS.users,userId,{followingCount:Math.max(0,Number(me.followingCount||0)-1)}),databases.updateDocument(DATABASE_ID,COLLECTIONS.users,targetUserId,{followersCount:Math.max(0,Number(target.followersCount||0)-1)})])}
export async function isFollowing(userId,targetUserId){if(!userId||!targetUserId)return false;const r=await databases.listDocuments(DATABASE_ID,COLLECTIONS.follows,[Query.equal('userId',userId),Query.equal('targetUserId',targetUserId),Query.limit(1)]);return !!r.documents.length}
export async function listActivity(userId){const out=[];for(const [key,col,field] of [['joins',COLLECTIONS.participants,'userId'],['reactions',COLLECTIONS.reactions,'userId'],['comments',COLLECTIONS.comments,'userId']]){try{const r=await databases.listDocuments(DATABASE_ID,col,[Query.equal(field,userId),Query.orderDesc('createdAt'),Query.limit(10)]);r.documents.forEach(x=>out.push({...x,_type:key}))}catch{}}return out.sort((a,b)=>new Date(b.createdAt||b.$createdAt)-new Date(a.createdAt||a.$createdAt)).slice(0,20)}
export { ID, Query, COLLECTIONS, DATABASE_ID }
